name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Checkout
        uses: actions/setup-node@v1
        with:
         node-version: 10.x
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.88.1'
      - name: Prepare Hugo
        run: |
            git submodule sync && git submodule update --init
      - name: Build
        run: make docs
        
#      - name: add nojekyll
#        run: touch ./docs/public/.nojekyll
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          emptyCommits: false
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/public
